Repository cahirwpz/mimiker, pull requests merged in 2018-05, with the labels that each got.

#419 Testing Coprocessor Unusable and Reserved Instruction exception in userspace.
  mips/intr.c
  tests/utest.c
  user/utest/Makefile
  user/utest/exceptions.c
  user/utest/main.c
  user/utest/utest.h
Labels: maintainer

#429 Switched to in_kernel_mode function
  mips/intr.c
Labels: cleanup

#431 Testing Floating Point, Unaligned Access exceptions and wrong syscall number behaviour.
  include/signal.h
  tests/utest.c
  user/utest/exceptions.c
  user/utest/main.c
  user/utest/misbehave.c
  user/utest/utest.h
Labels: maintainer

#410 Tests for preserving FPU context across processes using FPU.
  tests/utest.c
  user/utest/Makefile
  user/utest/fpu_ctx.c
  user/utest/main.c
  user/utest/utest.c
  user/utest/utest.h
Labels: blocked, not ready

#444 Disable interrupts & don't generate exceptions when accessing TLB
  debug/cpu.py
  mips/tlb.c
Labels: maintainer
