Repository cahirwpz/mimiker, pull requests merged in 2018-07, with the labels that each got.

#446 vm_map: API rework & synchronization
  include/errno.h
  include/mips/pmap.h
  include/mman.h
  include/vm.h
  include/vm_map.h
  include/vm_object.h
  include/vm_pager.h
  sys/exec.c
  sys/mmap.c
  sys/sbrk.c
  sys/sysent.c
  sys/vm_map.c
  sys/vm_object.c
  sys/vm_pager.c
  tests/vm_map.c
  user/utest/mmap.c
  user/utest/sbrk.c
Labels: maintainer

#441 Detect kernel stack overflow in kern_exc_enter and panic when it happens.
  mips/exc.S
  mips/intr.c
Labels: WIP

#366 clock_gettime, nanosleep and gettimeofday syscalls
  include/sysent.h
  include/time.h
  sys/Makefile
  sys/sysent.c
  sys/time.c
  user/libmimiker/Makefile
  user/libmimiker/gettimeofday.c
  user/libmimiker/nanosleep.c
  user/libmimiker/syscalls.S
Labels: WIP, feature

#458 Update ISA drivers to allocate port ranges
  include/bus.h
  include/device.h
  include/mips/_bus.h
  include/rman.h
  mips/cbus.c
  mips/gt64120.c
  mips/rootdev.c
  mips/uart_cbus.c
  sys/bus.c
  sys/devfs.c
  sys/device.c
  sys/drv_atkbdc.c
  sys/drv_pit.c
  sys/drv_rtc.c
  sys/drv_stdvga.c
  sys/rman.c
Labels: WIP, bug
