Repository cahirwpz/mimiker, pull requests merged in 2019-01, with the labels that each got.

#502 Cannot kmalloc blocks larger than PAGESIZE
  sys/malloc.c
  tests/malloc.c
Labels: bug

#522 tmux-based launch program
  .gdbinit
  .tmux.conf
  README.md
  debug/__init__.py
  debug/cpu.py
  debug/ctx.py
  debug/kdump.py
  debug/klog.py
  debug/ktrace.py
  debug/physmem.py
  debug/sync.py
  debug/thread.py
  launch
  launcher/__init__.py
  launcher/common.py
  launcher/debuggers.py
  launcher/outputs.py
  launcher/simulators.py
  run_tests.py
Labels: WIP

#524 Fix group id in Dockerfile
  docker/Dockerfile.tpl
Labels: bug, docker
