Repository cahirwpz/mimiker, pull requests merged in 2019-11, with the labels that each got.

#575 Glue kernel-space backtrace with user-space backtrace.
  .gdbinit
  include/mips/asm.h
  include/mips/exc.h
  sys/mips/copy.S
  sys/mips/exc.S
  sys/mips/sigcode.S
Labels: debug, feature

#581 Fixed python gdb $process() function
  sys/debug/proc.py
Labels: debug-infra, fix

#589 Separate debug symbols in sysroot
  Makefile
  bin/lua/Makefile
  build/build.prog.mk
Labels: debug-infra

#591 Load symbols automatically on startup
  .gdbinit
  launch
  launcher/__init__.py
Labels: debug-infra, feature

#593 vmem: comments & simplify vmem_alloc & little refactor
  include/sys/vmem.h
  sys/kern/vmem.c
Labels: cleanup, documentation

#595 kfree should do nothing when NULL is passed
  sys/kern/malloc.c
Labels: bug, fix

#457 MIPS CPU timer implementation
  include/sys/time.h
  sys/mips/timer.c
Labels: bug

#607 Fixing #594. Do not deliver signals to zombies, ...
  sys/kern/proc.c
  sys/kern/signal.c
Labels: fix
