Repository cahirwpz/mimiker, pull requests merged in 2019-02, with the labels that each got.

#498 Move kernel switch context on kernel stack
  include/mips/ctx.h
  include/thread.h
  mips/boot.S
  mips/genassym.c
  mips/switch.S
  sys/sched.c
  sys/thread.c
Labels: proposal

#529 Several improvements to gdb infrastructure
  debug/__init__.py
  debug/cmd.py
  debug/klog.py
  debug/proc.py
  debug/thread.py
Labels: WIP

#517 Process groups implementation.
  include/proc.h
  sys/exec.c
  sys/fork.c
  sys/proc.c
  sys/sysent.c
Labels: feature

#525 Proper locking of proc_t
  include/proc.h
  sys/fork.c
  sys/main.c
  sys/proc.c
  sys/sbrk.c
  tests/utest.c
Labels: bug
