Repository cahirwpz/mimiker, pull requests merged in 2021-02, with the labels that each got.

#951 Add various library routines required to port libterminfo
  include/cdbr.h
  include/cdbw.h
  include/stdlib.h
  include/sys/bitops.h
  include/sys/endian.h
  lib/libc/Makefile
  lib/libc/cdb/cdbr.c
  lib/libc/cdb/cdbw.c
  lib/libc/stdlib/mi_vector_hash.c
Labels: accepted

#978 Get program counter from context
  include/sys/context.h
  sys/aarch64/context.c
  sys/mips/context.c
Labels: accepted

#948 PCI isn't a PCI attached device.
  sys/drv/ns16550.c
  sys/mips/gt64120.c
  sys/mips/rootdev.c
Labels: accepted

#977 Introduce ringbuf_getnb.
  include/sys/ringbuf.h
  sys/kern/ringbuf.c
Labels: accepted

#971 Fully control test-run using gdb.
  .gdbinit-test
  .github/workflows/default.yml
  launch
  launcher/__init__.py
  run_tests.py
  sys/debug/cmd.py
  sys/kern/ktest.c
  sys/kern/main.c
Labels: review

#983 Fix unwanted interrupt recursion.
  sys/kern/interrupt.c
Labels: WiP

#970 tmpfs: Add file access, modify and change times
  include/sys/cred.h
  include/sys/time.h
  include/sys/vnode.h
  sys/kern/cred_checks.c
  sys/kern/initrd.c
  sys/kern/time.c
  sys/kern/tmpfs.c
  sys/kern/vfs_vnode.c
Labels: accepted

#976 Read subclass code and programming interface fields from PCI configuration space.
  include/sys/pci.h
  sys/kern/pci.c
Labels: accepted

#988 rtl8139 qemu config
  .gitignore
  launch
Labels: accepted

#984 Add utimens-like syscalls
  include/sys/stat.h
  include/sys/syscall.h
  include/sys/syscallargs.h
  include/sys/vfs.h
  lib/libc/sys/lutimens.c
  lib/libc/sys/missing.S
  lib/libc/sys/utimens.c
  sys/kern/syscalls.c
  sys/kern/syscalls.master
  sys/kern/sysent.h
  sys/kern/vfs_syscalls.c
Labels: accepted

#929 Add various functionality required to port the `script` program.
  include/stdlib.h
  include/sys/cdefs.h
  include/sys/endian.h
  include/sys/tty.h
  include/sys/ttycom.h
  include/util.h
  lib/libutil/Makefile
  lib/libutil/login_tty.c
  lib/libutil/pty.c
  sys/kern/tty.c
Labels: accepted

#873 ISA bus driver for Malta
  sys/drv/atkbdc.c
  sys/drv/ns16550.c
  sys/drv/pit.c
  sys/drv/rtc.c
  sys/kern/Makefile
  sys/kern/isa.c
  sys/mips/82371AB.c
  sys/mips/Makefile
  sys/mips/gt64120.c
Labels: accepted

#919 TTY & PTY userspace tests
  bin/utest/Makefile
  bin/utest/main.c
  bin/utest/pty.c
  bin/utest/tty.c
  bin/utest/utest.h
  bin/utest/util.c
  bin/utest/util.h
  sys/kern/tty.c
  sys/tests/utest.c
Labels: accepted

#956 Fix lock order in pmap
  sys/aarch64/pmap.c
  sys/mips/pmap.c
Labels: review

#934 pmap: fix bug with permissions
  bin/utest/main.c
  bin/utest/mmap.c
  bin/utest/utest.h
  include/mips/tlb.h
  include/sys/pmap.h
  sys/mips/pmap.c
  sys/mips/trap.c
  sys/tests/utest.c
Labels: accepted

#955 AArch64: pmap emulate bits
  include/aarch64/pte.h
  sys/aarch64/gpio.c
  sys/aarch64/pmap.c
  sys/aarch64/trap.c
Labels: AArch64

#993 AArch64: disable interrupts in user_exc_leave.
  build/common.mk
  include/aarch64/armreg.h
  lib/libc/aarch64/genassym.cf
  lib/libc/gen/aarch64/setjmp.S
  sys/aarch64/evec.S
  sys/aarch64/genassym.cf
  sys/aarch64/interrupt.c
  sys/aarch64/switch.S
  sys/aarch64/trap.c
Labels: AArch64, review

#997 Implement readv() and writev() syscalls
  bin/utest/fd.c
  bin/utest/main.c
  bin/utest/utest.h
  include/sys/syscall.h
  include/sys/syscallargs.h
  include/sys/uio.h
  lib/libc/sys/syscalls.S
  sys/kern/syscalls.c
  sys/kern/syscalls.master
  sys/kern/sysent.h
  sys/kern/uio.c
  sys/tests/utest.c
Labels: review

#973 Port `script` program from NetBSD
  include/sys/wait.h
  lib/libc/gen/wait.c
  usr.bin/Makefile
  usr.bin/script/Makefile
  usr.bin/script/script.c
Labels: accepted

#995 AArch64: validate status register in setcontext syscall.
  include/aarch64/armreg.h
  lib/libc/aarch64/genassym.cf
  lib/libc/gen/aarch64/longjmp.c
  sys/aarch64/context.c
  sys/aarch64/evec.S
Labels: AArch64, accepted

#890 RTL8139: first version of rx-interrupt handler
  include/dev/rtl8139_reg.h
  sys/drv/rtl8139.c
Labels: review

#994 AArch64: map kernel pages with VM_PROT_NONE without read permissions.
  include/aarch64/pte.h
  sys/aarch64/boot.c
  sys/aarch64/pmap.c
Labels: AArch64, accepted

#982 AArch64: run tests in CI.
  .github/workflows/default.yml
  sys/tests/utest.c
Labels: AArch64, accepted

#1000 Fix deadlock caused by call to pmap_page_remove in pm_free_from_seg
  include/sys/vm.h
  include/sys/vm_object.h
  include/sys/vm_physmem.h
  sys/kern/kmem.c
  sys/kern/vm_map.c
  sys/kern/vm_object.c
  sys/kern/vm_physmem.c
Labels: critical, review

#1012 Implement sigpend() syscall, make test_signal_mask() more resilient
  bin/utest/signal.c
  include/sys/signal.h
  include/sys/syscall.h
  include/sys/syscallargs.h
  lib/libc/sys/syscalls.S
  sys/kern/signal.c
  sys/kern/syscalls.c
  sys/kern/syscalls.master
  sys/kern/sysent.h
Labels: review

#1010 AArch64/dbg: adjust ctx.py to AArch64.
  sys/debug/ctx.py
Labels: AArch64, accepted

#897 toolchain: update qemu from 4.1.0 to 5.2.0
  Dockerfile
  toolchain/qemu-mimiker/Makefile
  toolchain/qemu-mimiker/README.md
  toolchain/qemu-mimiker/debian/changelog
  toolchain/qemu-mimiker/patches/fix-virtual-clock-in-gdb.patch
  toolchain/qemu-mimiker/patches/page-table-walk-for-gdb.patch
Labels: WiP

#1011 Enable icount with shift=auto, increase timeout for KASAN tests
  .github/workflows/default.yml
  launch
  run_tests.py
Labels: accepted

#1014 tty/pl011: basic TTY implementation for pl011.
  launch
  sys/aarch64/pl011.c
Labels: review

#1022 pgrp_maybe_orphan(): send SIGHUP + SIGCONT to all members of pgrp if any member is stopped
  sys/kern/proc.c
Labels: review

#950 Allow callouts to be rescheduled from the callback
  include/sys/callout.h
  sys/kern/callout.c
  sys/kern/sleepq.c
  sys/tests/callout.c
  sys/tests/sleepq.c
Labels: accepted

#1001 Simplify control flow in sig_kill()
  include/sys/proc.h
  sys/kern/proc.c
  sys/kern/signal.c
  sys/kern/thread.c
Labels: review
