Repository cahirwpz/mimiker, pull requests merged in 2021-05, with the labels that each got.

#1095 [evdev 2/3] Introduce evdev - generic input event interface
  include/dev/evdev.h
  include/sys/ioccom.h
  sys/drv/Makefile
  sys/drv/atkbdc.c
  sys/drv/evdev.c
  sys/drv/evdev_kbd.c
Labels: accepted

#1102 graphics: change the interface of VGA
  bin/mandelbrot/mandelbrot.c
  build/build.prog.mk
  contrib/doom/01-vga-output.patch
  include/dev/vga.h
  include/sys/fb.h
  sys/drv/Makefile
  sys/drv/dev_vga.c
  sys/drv/stdvga.c
Labels: accepted

#1105 Move ioflags from VOP_READ/WRITE arguments into uio::uio_ioflags
  include/sys/file.h
  include/sys/uio.h
  include/sys/vnode.h
  sys/drv/dev_cons.c
  sys/drv/evdev.c
  sys/drv/rtc.c
  sys/drv/stdvga.c
  sys/kern/dev_null.c
  sys/kern/dev_procstat.c
  sys/kern/exec_elf.c
  sys/kern/exec_shebang.c
  sys/kern/file.c
  sys/kern/file_syscalls.c
  sys/kern/initrd.c
  sys/kern/pipe.c
  sys/kern/pty.c
  sys/kern/tmpfs.c
  sys/kern/vfs_vnode.c
  sys/tests/vfs.c
Labels: accepted

#1107 Fix kmem_map_contig invocation.
  sys/kern/kmem.c
Labels: accepted, bug

#1108 Remove an assert in add_slab.
  sys/kern/pool.c
Labels: accepted, bug

#1112 Update USB headers.
  include/dev/uhci.h
  include/dev/usb.h
  include/dev/usbhc.h
  include/dev/usbhid.h
Labels: accepted

#1123 Implement sync and fsync syscalls as NOPs
  include/sys/syscall.h
  include/sys/syscallargs.h
  lib/libc/sys/missing.S
  lib/libc/sys/syscalls.S
  sys/kern/syscalls.c
  sys/kern/syscalls.master
  sys/kern/sysent.h
Labels: review

#1100 Add assertion in kgprof.c
  sys/kern/kgprof.c
Labels: accepted

#1086 Rewrite munmap
  bin/utest/main.c
  bin/utest/mmap.c
  bin/utest/utest.h
  include/sys/vm_map.h
  sys/debug/virtmem.py
  sys/kern/mmap.c
  sys/kern/vm_map.c
  sys/tests/utest.c
Labels: accepted

#1113 Introduce USB interfaces.
  include/dev/usb.h
  include/sys/device.h
Labels: review

#1062 Function instrumentation for kgprof - MIPS
  build/arch.mips.mk
  build/common.mk
  include/sys/cdefs.h
  include/sys/context.h
  include/sys/cpu.h
  include/sys/gmon.h
  include/sys/interrupt.h
  include/sys/mimiker.h
  include/sys/spinlock.h
  include/sys/thread.h
  sys/aarch64/context.c
  sys/aarch64/interrupt.c
  sys/debug/kgmon.py
  sys/kern/Makefile
  sys/kern/interrupt.c
  sys/kern/kgprof.c
  sys/kern/mcount.c
  sys/kern/spinlock.c
  sys/kern/thread.c
  sys/libkern/copystr.c
  sys/mips/Makefile
  sys/mips/context.c
  sys/mips/interrupt.c
  sys/mips/trap.c
Labels: accepted

#1103 Introduce device file nodes.
  include/sys/devfs.h
  include/sys/refcnt.h
  include/sys/vnode.h
  sys/drv/rtc.c
  sys/drv/stdvga.c
  sys/kern/devfs.c
  sys/kern/vfs_vnode.c
Labels: review

#1120 [kevent 1/5] Add header file for kevent
  include/sys/event.h
  include/sys/file.h
Labels: accepted

#1111 Tags standard wiki page
  wiki/docs/commenting.md
Labels: accepted

#1121 [kevent 2/5] Add prerequisites for kevent
  include/sys/filedesc.h
  include/sys/syscall.h
  include/sys/syscallargs.h
  include/sys/time.h
  lib/libc/sys/kqueue.c
  lib/libc/sys/syscalls.S
  sys/kern/Makefile
  sys/kern/event.c
  sys/kern/filedesc.c
  sys/kern/fork.c
  sys/kern/syscalls.c
  sys/kern/syscalls.master
  sys/kern/sysent.h
  sys/kern/time.c
Labels: accepted

#1094 AArch64/boot: use dtb instead of atags
  .github/workflows/default.yml
  include/aarch64/atags.h
  include/aarch64/pmap.h
  include/sys/dtb.h
  launch
  sys/Makefile
  sys/aarch64/board.c
  sys/aarch64/boot.c
  sys/aarch64/pmap.c
  sys/aarch64/start.S
  sys/dts/Makefile
  sys/dts/README.md
  sys/dts/rpi3.dts
  sys/kern/Makefile
  sys/kern/dtb.c
  sys/kern/main.c
Labels: AArch64, accepted

#1130 Set window size on shell startup only if it isn't already set
  etc/.kshrc
Labels: review

#1140 Fix setreuid
  sys/kern/cred_syscalls.c
Labels: review

#1117 Add the alignment feature to the pool allocator.
  build/flags.mk
  include/sys/pool.h
  sys/kern/pool.c
  sys/tests/pool.c
Labels: review

#1109 UHCI host controller driver.
  include/sys/time.h
  sys/drv/Makefile
  sys/drv/uhci.c
  sys/drv/usb.c
  sys/kern/time.c
Labels: accepted

#1145 build: keep kernel image after compression
  build/arch.aarch64.mk
  sys/Makefile
Labels: AArch64, accepted
