Repository cahirwpz/mimiker, pull requests merged in 2021-06, with the labels that each got.

#1144 dtb: fix absolutely shitty behavior of bootloaders
  sys/kern/dtb.c
Labels: review

#1119 `SIGPIPE` tests
  bin/utest/Makefile
  bin/utest/main.c
  bin/utest/pipe.c
  bin/utest/utest.h
  sys/kern/file_syscalls.c
  sys/kern/pipe.c
  sys/tests/utest.c
Labels: accepted

#1151 elf: remove unnecessary bzero
  sys/kern/exec_elf.c
Labels: accepted

#1146 aarch64/bcopy: remove not aligned access to memory
  build/arch.aarch64.mk
Labels: AArch64, accepted

#867 KCSAN
  README.md
  build/common.mk
  build/flags.kern.mk
  config.mk
  include/sys/cdefs.h
  include/sys/kcsan.h
  sys/aarch64/Makefile
  sys/kern/Makefile
  sys/kern/kcsan.c
  sys/kern/main.c
  sys/kern/sched.c
  sys/kern/thread.c
  sys/mips/Makefile
Labels: accepted

#1115 Introduce device_remove_child.
  include/sys/device.h
  sys/kern/device.c
Labels: accepted

#1152 USB headers update.
  include/dev/usb.h
  include/dev/usbhc.h
  sys/drv/uhci.c
Labels: accepted

#1114 USB bus driver.
  sys/drv/usb.c
Labels: accepted

#1104 Fix authorization during change of file timestamps
  include/sys/cred.h
  include/sys/vnode.h
  sys/kern/cred_checks.c
  sys/kern/tmpfs.c
  sys/kern/vfs_syscalls.c
  sys/kern/vfs_vnode.c
Labels: accepted

#1098 Onboarding note
  wiki/docs/_Sidebar.md
  wiki/docs/onboarding.md
Labels: review

#1155 Kgmon fix
  sys/debug/kgmon.py
Labels: review

#1158 Store temporary userspace vm_map in process in paging_on_demand_and_memory_protection_demo()
  sys/tests/vm_map.c
Labels: bug, review

#1160 Make pipe I/O operations interruptible by signals.
  sys/kern/pipe.c
Labels: review
