Repository cahirwpz/mimiker, pull requests merged in 2021-04, with the labels that each got.

#1078 Run mimiker without the debug option.
  launch
Labels: accepted, bug

#1079 Remove MD bus definitions.
  include/aarch64/bus_defs.h
  include/mips/bus_defs.h
  include/sys/bus.h
  include/sys/bus_defs.h
  include/sys/rman.h
Labels: accepted

#1051 Wiki deployment script with new wiki folder
  .github/workflows/deploy_wiki.yml
  .gitignore
  wiki/docs/Home.md
  wiki/docs/_Sidebar.md
  wiki/entrypoint.sh
Labels: accepted

#1069 Clean vm_object interface
  include/sys/vm.h
  include/sys/vm_object.h
  sys/kern/vm_map.c
  sys/kern/vm_object.c
Labels: accepted

#1075 cred: fix prototype of cred_can_access
  include/sys/cred.h
  include/sys/vnode.h
  sys/kern/cred_checks.c
  sys/kern/vfs_vnode.c
  sys/tests/devfs.c
Labels: accepted

#1088 Change adjacency assertions in vmem_free.
  sys/kern/vmem.c
Labels: review

#1057 e.MMC interface
  include/dev/emmc.h
  include/sys/device.h
  sys/drv/emmc.c
Labels: review

#1077 Extract MI signatures form MD interrupt.h.
  include/aarch64/interrupt.h
  include/mips/interrupt.h
  include/sys/cpu.h
  sys/aarch64/interrupt.c
  sys/aarch64/rootdev.c
  sys/aarch64/timer.c
  sys/aarch64/trap.c
  sys/kern/interrupt.c
  sys/mips/gt64120.c
  sys/mips/interrupt.c
  sys/mips/malta.c
  sys/mips/timer.c
  sys/mips/trap.c
Labels: accepted

#1061 USB host controller interface.
  include/dev/usb.h
  include/dev/usbhc.h
  include/sys/device.h
Labels: accepted

#1090 build: adjust build system for multiple config options
  build/build.kern.mk
  build/common.mk
  build/compile.mk
  config.mk
  include/dev/bcm2835_gpio.h
  include/dev/bcm2835_gpioreg.h
  include/dev/bcm2835reg.h
  include/dev/malta.h
  include/dev/pci.h
  include/dev/plcomreg.h
  include/dev/uart.h
  include/dev/vga.h
  include/sys/lockdep.h
  sys/Makefile
  sys/aarch64/Makefile
  sys/aarch64/aarch64.ld
  sys/aarch64/board.c
  sys/aarch64/timer.c
  sys/drv/82371AB.c
  sys/drv/Makefile
  sys/drv/atkbdc.c
  sys/drv/bcm2835_gpio.c
  sys/drv/bcm2835_rootdev.c
  sys/drv/cbus.c
  sys/drv/dev_cons.c
  sys/drv/dev_vga.c
  sys/drv/gt64120.c
  sys/drv/isa.c
  sys/drv/malta_rootdev.c
  sys/drv/ns16550.c
  sys/drv/pci.c
  sys/drv/pci_ids.c
  sys/drv/pit.c
  sys/drv/pl011.c
  sys/drv/rtc.c
  sys/drv/rtl8139.c
  sys/drv/stdvga.c
  sys/drv/uart.c
  sys/drv/uart_cbus.c
  sys/kern/Makefile
  sys/kern/lockdep.c
  sys/kern/main.c
  sys/kern/uart_tty.c
  sys/mips/Makefile
  sys/mips/board.c
  sys/mips/boot.c
  sys/mips/mips.ld
Labels: accepted

#1093 [evdev 1/3] Add prerequisites for evdev
  include/dirent.h
  include/sys/input-event-codes.h
  include/sys/input.h
  lib/libc/gen/scandir.c
Labels: accepted

#1081 Rename some structures and fields in VM subsystem
  include/sys/proc.h
  include/sys/vm.h
  include/sys/vm_map.h
  include/sys/vm_object.h
  sys/kern/exec.c
  sys/kern/exec_elf.c
  sys/kern/fork.c
  sys/kern/mmap.c
  sys/kern/sbrk.c
  sys/kern/vm_map.c
  sys/kern/vm_object.c
  sys/tests/vm_map.c
Labels: accepted

#1087 Ensure page alignment in KVM mapping routine and make "contig" functions more compact.
  sys/kern/kmem.c
Labels: review

#1092 Fix pool allocator.
  sys/kern/pool.c
Labels: accepted, bug

#1099 aarch64/pmap: fix pmap_kremove
  sys/aarch64/pmap.c
Labels: AArch64, bug
