Repository cahirwpz/mimiker, pull requests merged in 2021-01, with the labels that each got.

#887 Simplify context in user space (part 3)
  include/aarch64/setjmp.h
  include/mips/mcontext.h
  include/mips/regdef.h
  include/mips/setjmp.h
  include/setjmp.h
  lib/libc/gen/aarch64/sigsetjmp.S
  lib/libc/gen/mips/_setjmp.S
  lib/libc/gen/mips/setjmp.S
  lib/libc/gen/mips/sigsetjmp.S
  lib/libc/mips/genassym.cf
Labels: accepted

#851 Signals for AArch64.
  include/aarch64/asm.h
  sys/aarch64/Makefile
  sys/aarch64/sigcode.S
  sys/aarch64/signal.c
  sys/kern/exec.c
  sys/kern/signal.c
  sys/mips/sigcode.S
  sys/mips/signal.c
Labels: AArch64, accepted

#829 PIT timer with 64 bit counter
  include/sys/timer.h
  sys/drv/pit.c
  sys/mips/timer.c
Labels: accepted

#915 Get pwcache from NetBSD
  lib/libc/gen/pwcache.c
  lib/libc/gen/pwcache.h
Labels: accepted

#918 Add FIONREAD ioctl
  include/sys/filio.h
  sys/kern/tty.c
Labels: review

#902 Handle signals in the TTY layer using ERESTARTSYS
  include/sys/tty.h
  sys/kern/tty.c
Labels: review

#925 Allow to set set-user-id bit on userspace programs
  build/build.prog.mk
  usr.bin/su/Makefile
Labels: review

#880 AArch64: non-local jumps
  include/aarch64/abi.h
  lib/libc/aarch64/genassym.cf
  lib/libc/gen/aarch64/_setjmp.S
  lib/libc/gen/aarch64/longjmp.c
  lib/libc/gen/aarch64/setjmp.S
  lib/libc/gen/aarch64/sigsetjmp.S
  lib/libc/gen/mips/longjmp.c
Labels: AArch64, accepted

#933 Remove unnecessary ICU_LEN from gt64120 driver
  sys/mips/gt64120.c
Labels: accepted

#926 Fix files and directory ownership
  sys/kern/vfs_syscalls.c
Labels: accepted

#920 Add getpass(), getpass_r() and getpassfd() from NetBSD
  include/unistd.h
  lib/libc/gen/getpass.c
Labels: accepted

#923 Implement TIOCGWINSZ and TIOCSWINSZ ioctls
  include/sys/signal.h
  include/sys/tty.h
  sys/kern/signal.c
  sys/kern/tty.c
Labels: accepted

#916 tty: add support for ISIG flag (i.e. send signals in response to certain control characters)
  include/sys/ttydefaults.h
  sys/kern/signal.c
  sys/kern/tty.c
Labels: accepted

#721 Nanosleep syscall.
  bin/utest/main.c
  bin/utest/time.c
  bin/utest/utest.h
  include/sys/time.h
  lib/libc/sys/nanosleep.c
  sys/kern/syscalls.c
  sys/kern/time.c
  sys/tests/utest.c
Labels: accepted

#908 munmap: allow munmapping pieces of segments
  bin/utest/mmap.c
  include/sys/vm_map.h
  sys/kern/mmap.c
  sys/kern/vm_map.c
Labels: accepted

#921 Progressive device tree scanning.
  include/sys/bus.h
  include/sys/device.h
  sys/aarch64/pl011.c
  sys/aarch64/rootdev.c
  sys/aarch64/timer.c
  sys/drv/atkbdc.c
  sys/drv/ns16550.c
  sys/drv/pit.c
  sys/drv/rtc.c
  sys/drv/rtl8139.c
  sys/drv/stdvga.c
  sys/kern/bus.c
  sys/kern/main.c
  sys/mips/gt64120.c
  sys/mips/rootdev.c
  sys/mips/timer.c
Labels: accepted

#922 Add an attribute to disable the compiler instrumentation
  include/sys/cdefs.h
  include/sys/mimiker.h
  sys/libkern/Makefile
  sys/libkern/copystr.c
Labels: review

#917 Reorganize hardware resources handling.
  include/sys/bus.h
  include/sys/device.h
  include/sys/pci.h
  include/sys/rman.h
  sys/aarch64/pl011.c
  sys/aarch64/rootdev.c
  sys/kern/bus.c
  sys/kern/device.c
  sys/kern/rman.c
  sys/mips/cbus.c
  sys/mips/gt64120.c
  sys/mips/rootdev.c
Labels: accepted

#943 Round up memory bars to the page size boundary.
  sys/kern/pci.c
  sys/mips/gt64120.c
Labels: accepted

#941 AArch64: use virtual address instead of physical address in tlb_invalidate.
  include/aarch64/tlb.h
  sys/aarch64/pmap.c
  sys/aarch64/tlb.c
Labels: AArch64, accepted

#927 Simplify PIT timer - remove spinlock
  sys/drv/pit.c
Labels: accepted

#936 AArch64: fix user-space sbrk test.
  bin/utest/sbrk.c
Labels: AArch64, review

#937 AArch64: fix user-space mmap test.
  bin/utest/mmap.c
Labels: AArch64, review

#942 AArch64: fix kernel-space findspace test.
  sys/tests/vm_map.c
Labels: AArch64, review

#898 Interrupt sharing.
  include/sys/bus.h
  include/sys/device.h
  include/sys/rman.h
  sys/kern/bus.c
  sys/kern/rman.c
  sys/mips/gt64120.c
Labels: accepted

#947 Fix PCI configuration space reading/writing.
  include/sys/pci.h
  sys/mips/gt64120.c
Labels: accepted

#952 test_sleepq_timed(): fix race on shared variable.
  sys/tests/sleepq_timed.c
Labels: review

#930 Fix gdb `kthread` command
  sys/debug/ctx.py
  sys/debug/struct.py
  sys/debug/thread.py
Labels: accepted

#928 Save FPU context on ctx_switch, restore on user_exc_leave.
  include/sys/thread.h
  sys/mips/ebase.S
  sys/mips/genassym.cf
  sys/mips/switch.S
  sys/mips/trap.c
Labels: accepted

#949 Login: changes in libc and headers
  include/paths.h
  include/pwd.h
  include/sys/file.h
  include/sys/param.h
  include/sysexits.h
  include/unistd.h
  lib/libc/gen/execlp.c
  lib/libc/gen/ttyname.c
Labels: accepted

#895 gt64120: route PCI interrupts to i8259
  include/sys/pci.h
  sys/kern/pci.c
  sys/mips/gt64120.c
Labels: accepted

#962 Allow fstat() on file descriptors without read access
  sys/kern/file_syscalls.c
Labels: accepted

#960 Handle errors generated by VOP_GETATTR
  sys/kern/vfs_syscalls.c
Labels: accepted

#958 proc: zero session structs before use
  sys/kern/proc.c
Labels: accepted

#957 klog: fix race
  include/sys/klog.h
  sys/kern/klog.c
Labels: KCSAN, accepted

#967 Migrate from CircleCI to GitHub Actions!
  .circleci/config.yml
  .github/workflows/default.yml
  build/tools.mk
  launch
  launcher/__init__.py
  run_tests.py
Labels: review

#961 gt64120: fix PCI interrupt routing.
  sys/kern/pci.c
Labels: accepted

#966 AArch64: set user-space return address in setcontext
  lib/libc/gen/aarch64/longjmp.c
  sys/aarch64/context.c
Labels: AArch64, review

#945 Login program
  etc/master.passwd
  usr.bin/Makefile
  usr.bin/login/Makefile
  usr.bin/login/common.c
  usr.bin/login/common.h
  usr.bin/login/login.c
  usr.bin/login/pathnames.h
Labels: accepted

#959 Increase KTEST_NAME_MAX to 50.
  include/sys/ktest.h
Labels: accepted

#946 Sticky bit
  include/sys/vnode.h
  sys/kern/cred_checks.c
  sys/kern/main.c
  sys/kern/vfs_syscalls.c
Labels: accepted

#969 fchdir: release old cwd vnode
  sys/kern/vfs_syscalls.c
Labels: review

#931 AArch64: save FPU context on ctx_switch, restore on user_exc_leave.
  sys/aarch64/evec.S
  sys/aarch64/genassym.cf
  sys/aarch64/switch.S
  sys/aarch64/trap.c
Labels: AArch64, review

#910 Implement pseudoterminals
  include/stdlib.h
  include/sys/fcntl.h
  include/sys/file.h
  include/sys/proc.h
  include/sys/pty.h
  include/sys/syscall.h
  include/sys/syscallargs.h
  include/sys/tty.h
  include/sys/ttycom.h
  lib/libc/stdlib/pty.c
  lib/libc/sys/syscalls.S
  sys/kern/Makefile
  sys/kern/pty.c
  sys/kern/syscalls.c
  sys/kern/syscalls.master
  sys/kern/sysent.h
  sys/kern/tty.c
Labels: accepted
