Repository cahirwpz/mimiker, pull requests merged in 2021-03, with the labels that each got.

#1026 Prepare for implementing setitimer() and getitimer()
  include/sys/callout.h
  include/sys/syscall.h
  include/sys/syscallargs.h
  include/sys/time.h
  lib/libc/sys/missing.S
  lib/libc/sys/syscalls.S
  sys/kern/callout.c
  sys/kern/signal.c
  sys/kern/syscalls.c
  sys/kern/syscalls.master
  sys/kern/sysent.h
  sys/kern/time.c
  sys/tests/callout.c
Labels: review

#1029 proc_exit: don't call fdtab_drop() while holding p->p_lock
  sys/kern/proc.c
Labels: accepted

#1033 Removing the expensive HZ2BT operation in pit gettime
  sys/drv/pit.c
Labels: review

#1030 Simplify locking rules around pgrp_t::pg_lock
  include/sys/mutex.h
  include/sys/proc.h
  sys/kern/mutex.c
  sys/kern/proc.c
Labels: accepted

#1003 ringbuf_move[n]b to move data between two ringbuffers
  include/sys/ringbuf.h
  sys/kern/ringbuf.c
  sys/tests/ringbuf.c
Labels: accepted

#1031 Assert for vm_segment_destroy_range and simplyfing do_munmap
  sys/kern/mmap.c
  sys/kern/vm_map.c
Labels: accepted

#1008 Remove modulo operation (MIPS timer) & prefer MIPS timer over PIT
  sys/mips/timer.c
Labels: accepted

#1002 AArch64: exc tests.
  bin/utest/exceptions.c
  bin/utest/main.c
  bin/utest/utest.h
  include/aarch64/armreg.h
  sys/aarch64/boot.c
  sys/aarch64/trap.c
  sys/tests/utest.c
Labels: AArch64, accepted

#1023 Implement interval timers (setitimer() and getitimer() syscalls)
  bin/utest/main.c
  bin/utest/time.c
  bin/utest/utest.h
  include/sys/proc.h
  include/sys/time.h
  sys/kern/proc.c
  sys/kern/time.c
  sys/tests/utest.c
Labels: accepted

#974 Dev procstat
  bin/Makefile
  bin/ps/Makefile
  bin/ps/ps
  build/build.script.mk
  include/sys/proc.h
  include/sys/vnode.h
  sys/kern/Makefile
  sys/kern/dev_procstat.c
  sys/kern/proc.c
Labels: accepted

#1034 Remove MIN and MAX from kernel.
  include/sys/param.h
  sys/kern/dev_procstat.c
  sys/kern/initrd.c
  sys/kern/syscalls.c
  sys/kern/tmpfs.c
  sys/kern/tty.c
Labels: accepted

#1035 drivers: Convert PCI_BUS_METHODS and BUS_METHODS into functions.
  include/sys/bus.h
  include/sys/pci.h
  sys/kern/bus.c
  sys/mips/82371AB.c
Labels: accepted

#1039 Fix build & test run with -O2 optimization flag
  bin/utest/time.c
  sys/aarch64/sigcode.S
  sys/aarch64/signal.c
  sys/kern/exec.c
  sys/mips/sigcode.S
  sys/mips/signal.c
  sys/tests/fdt.c
Labels: accepted

#1032 Fix for counter overflow - arm timer
  sys/aarch64/timer.c
Labels: accepted

#975 Introduce basic USB related header files.
  include/dev/scsi.h
  include/dev/uhci.h
  include/dev/uhcireg.h
  include/dev/umass.h
  include/dev/usb.h
  include/dev/usbhid.h
Labels: accepted

#980 Port libterminfo from NetBSD
  include/term.h
  include/term_private.h
  include/termcap.h
  lib/Makefile
  lib/libterminfo/.gitignore
  lib/libterminfo/Makefile
  lib/libterminfo/compile.c
  lib/libterminfo/compiled_terms.c
  lib/libterminfo/curterm.c
  lib/libterminfo/genhash
  lib/libterminfo/genthash
  lib/libterminfo/setupterm.c
  lib/libterminfo/term.c
  lib/libterminfo/termcap.c
  lib/libterminfo/termcap_map.c
  lib/libterminfo/ti.c
  lib/libterminfo/tparm.c
  lib/libterminfo/tputs.c
Labels: accepted

#1042 Introduce MTX_DEFINE & SPIN_DEFINE macro
  include/sys/mutex.h
  include/sys/proc.h
  include/sys/spinlock.h
  sys/aarch64/pmap.c
  sys/kern/callout.c
  sys/kern/cred_checks.c
  sys/kern/dev_procstat.c
  sys/kern/devfs.c
  sys/kern/fork.c
  sys/kern/interrupt.c
  sys/kern/klog.c
  sys/kern/pool.c
  sys/kern/proc.c
  sys/kern/pty.c
  sys/kern/sched.c
  sys/kern/sleepq.c
  sys/kern/syscalls.c
  sys/kern/thread.c
  sys/kern/timer.c
  sys/kern/tmpfs.c
  sys/kern/tty.c
  sys/kern/turnstile.c
  sys/kern/vfs.c
  sys/kern/vm_physmem.c
  sys/kern/vmem.c
  sys/mips/pmap.c
  sys/tests/mutex.c
  sys/tests/turnstile_adjust.c
  sys/tests/turnstile_propagate_many.c
  sys/tests/turnstile_propagate_once.c
Labels: accepted

#1044 kstrndup(): always return null-terminated string.
  sys/kern/malloc.c
Labels: accepted, bug

#1020 New toolchain building method
  toolchain/.gitignore
  toolchain/Dockerfile
  toolchain/Makefile
  toolchain/README.md
  toolchain/common.py
  toolchain/gnu/.gitignore
  toolchain/gnu/Makefile
  toolchain/gnu/README.md
  toolchain/gnu/aarch64-mimiker-elf/Makefile
  toolchain/gnu/common.mk
  toolchain/gnu/config.mk
  toolchain/gnu/debian/changelog
  toolchain/gnu/debian/compat
  toolchain/gnu/debian/control
  toolchain/gnu/debian/install
  toolchain/gnu/debian/rules
  toolchain/gnu/mipsel-mimiker-elf/Makefile
  toolchain/gnu/target.mk
  toolchain/toolchain
Labels: review

#996 Lock dependency validator
  build/flags.kern.mk
  config.mk
  include/sys/lockdep.h
  include/sys/mutex.h
  include/sys/thread.h
  sys/kern/Makefile
  sys/kern/lockdep.c
  sys/kern/main.c
  sys/kern/mutex.c
Labels: accepted

#764 Introduce pmap_growkernel
  include/sys/kmem.h
  include/sys/pmap.h
  include/sys/types.h
  include/sys/vm.h
  sys/aarch64/pmap.c
  sys/kern/kmem.c
  sys/kern/vm_physmem.c
  sys/mips/pmap.c
Labels: accepted

#1019 uart: introduce generic uart interface to interact with tty.
  include/sys/device.h
  include/sys/tty.h
  include/sys/uart.h
  include/sys/uart_tty.h
  sys/aarch64/pl011.c
  sys/drv/ns16550.c
  sys/kern/Makefile
  sys/kern/uart.c
  sys/kern/uart_tty.c
Labels: accepted

#1040 KASAN: Dynamic shadow map size.
  include/mips/kasan.h
  include/sys/kasan.h
  sys/kern/kasan.c
  sys/mips/boot.c
  sys/mips/pmap.c
Labels: accepted

#987 Removing modulo operation from PIT.
  sys/drv/pit.c
Labels: accepted

#999 Make Mimiker compile under GCC11
  include/sys/stat.h
  include/unistd.h
  lib/libc/gen/getprogname.c
  sys/aarch64/boot.c
  sys/kern/vfs_syscalls.c
Labels: accepted

#1045 Remove redundant check in session_enter()
  sys/kern/proc.c
Labels: accepted

#1021 Timeout tests based on CPU time, not wall clock time
  launch
  requirements.txt
  toolchain/qemu-mimiker/patches/gdbstub-stop-on-sigxcpu.patch
  toolchain/qemu-mimiker/patches/series
Labels: accepted

#1050 Bump gcc version to 11
  Dockerfile
  toolchain/gnu/config.mk
Labels: accepted

#1024 Port tetris from NetBSD
  bin/Makefile
  bin/tetris/Makefile
  bin/tetris/input.c
  bin/tetris/input.h
  bin/tetris/pathnames.h
  bin/tetris/scores.c
  bin/tetris/scores.h
  bin/tetris/screen.c
  bin/tetris/screen.h
  bin/tetris/shapes.c
  bin/tetris/tetris.c
  bin/tetris/tetris.h
  sys/tests/callout.c
Labels: accepted

#1058 Remove rwlock.
  include/sys/rwlock.h
  sys/kern/Makefile
  sys/kern/rwlock.c
  sys/tests/Makefile
  sys/tests/rwlock.c
Labels: accepted

#979 Statclock and gprof structures initialization
  build/arch.mips.mk
  config.mk
  include/sys/gmon.h
  include/sys/kgprof.h
  include/sys/mimiker.h
  sys/debug/__init__.py
  sys/debug/kgmon.py
  sys/kern/Makefile
  sys/kern/clock.c
  sys/kern/kgprof.c
  sys/kern/main.c
Labels: accepted

#1049 Refine the build system.
  build/README.md
  build/arch.aarch64.mk
  build/arch.mips.mk
  build/build.kern.mk
  build/build.lib.mk
  build/build.prog.mk
  build/build.script.mk
  build/common.mk
  build/compile.mk
  build/flags.kern.mk
  build/flags.mk
  build/flags.user.mk
  build/tools.mk
  config.mk
  include/Makefile
  lib/libc/Makefile
  sys/Makefile
  sys/mips/.gitignore
  sys/mips/Makefile
Labels: accepted

#1053 Implement saving & restoring uio state
  include/sys/uio.h
  sys/kern/pty.c
  sys/kern/uio.c
  sys/tests/uiomove.c
Labels: accepted

#1043 Construct commandline during exec
  bin/ps/ps
  bin/utest/Makefile
  bin/utest/main.c
  bin/utest/procstat.c
  bin/utest/utest.h
  include/sys/proc.h
  include/sys/syslimits.h
  sys/kern/dev_procstat.c
  sys/kern/exec.c
  sys/kern/proc.c
  sys/tests/utest.c
Labels: accepted

#1055 Set window size on startup
  bin/Makefile
  bin/ksh/config.h
  bin/setwinsize/Makefile
  bin/setwinsize/setwinsize.c
  etc/.kshrc
  etc/Makefile
Labels: accepted

#1056 vm_boot_alloc(): don't let vm_kernel_end go past _kasan_sanitized_end
  include/sys/kasan.h
  sys/kern/vm_physmem.c
  sys/mips/boot.c
Labels: accepted

#1060 Add background checks to tty ioctls that modify tty settings
  sys/kern/tty.c
Labels: accepted

#1064 thread: increase stack size for 64 bit architectures
  include/aarch64/vm_param.h
  include/mips/vm_param.h
  sys/kern/thread.c
Labels: AArch64, accepted

#1065 CI: enable KASAN tests for AArch64
  .github/workflows/default.yml
  sys/aarch64/boot.c
  sys/kern/vmem.c
Labels: AArch64, review

#1059 Add the AMD64 QEMU target.
  toolchain/qemu-mimiker/Makefile
  toolchain/qemu-mimiker/debian/changelog
Labels: AMD64, accepted

#1054 Extend the toolchain of the AMD64 release.
  toolchain/gnu/Makefile
  toolchain/gnu/README.md
  toolchain/gnu/aarch64-mimiker-elf/Makefile
  toolchain/gnu/amd64-mimiker-elf/Makefile
  toolchain/gnu/config.mk
  toolchain/gnu/debian/changelog
  toolchain/gnu/debian/control
  toolchain/gnu/debian/install
  toolchain/gnu/mipsel-mimiker-elf/Makefile
  toolchain/gnu/target.mk
Labels: AMD64, accepted

#1038 Preserve value of x18 register across kernel interrupts.
  sys/aarch64/evec.S
Labels: accepted

#1067 ksh/history.c: silence warning during compilation with -O2
  bin/ksh/Makefile
Labels: accepted
