Repository cahirwpz/mimiker, pull requests merged in 2022-01, with the labels that each got.

#1195 [tools] update ackrc
  .ackrc
Labels: review

#1193 [DTB] Establish DTB target based on BOARD variable.
  sys/dts/Makefile
Labels: accepted

#1196 [arch/mips/malta] remove malta.dts
  sys/mips/malta.dts
Labels: review

#1192 [TESTS] Check pointer size instead of architecture in memory related tests
  bin/utest/mmap.c
  bin/utest/sbrk.c
  sys/kern/kcsan.c
  sys/tests/vm_map.c
Labels: accepted

#1201 [includes] Remove md cdefs.
  include/aarch64/asm.h
  include/aarch64/cdefs.h
  include/mips/asm.h
  include/mips/cdefs.h
  include/sys/cdefs.h
  include/sys/param.h
  lib/libc/gen/mips/_setjmp.S
Labels: accepted

#1205 [klog] fix klog format for tid_t
  sys/kern/proc.c
  sys/kern/signal.c
  sys/kern/sleepq.c
  sys/kern/thread.c
Labels: review

#1176 [RISCV] RISC-V Mimiker setup
  build/arch.riscv.mk
  config.mk
  include/Makefile
  include/riscv/abi.h
  include/riscv/asm.h
  include/riscv/elf_machdep.h
  include/riscv/int_const.h
  include/riscv/int_fmtio.h
  include/riscv/int_mwgwtypes.h
  include/riscv/limits.h
  include/riscv/mcontext.h
  include/riscv/pcpu.h
  include/riscv/syscall.h
  include/riscv/types.h
  include/riscv/vm_param.h
  launch
  lib/csu/riscv/crt0.S
  lib/csu/riscv/ld.script
  lib/libc/gen/riscv/longjmp.c
  lib/libc/gen/riscv/setjmp.S
  lib/libc/gen/riscv/sigsetjmp.S
  lib/libc/riscv/genassym.cf
  lib/libc/string/riscv/bcopy.S
  lib/libc/string/riscv/memcpy.S
  lib/libc/string/riscv/memmove.S
  lib/libc/string/riscv/strlen.S
  sys/Makefile
  sys/drv/Makefile
  sys/drv/litex_riscv_rootdev.c
  sys/riscv/.gitignore
  sys/riscv/Makefile
  sys/riscv/boot.c
  sys/riscv/copy.S
  sys/riscv/exception.S
  sys/riscv/genassym.cf
  sys/riscv/interrupt.c
  sys/riscv/mcontext.c
  sys/riscv/pmap.c
  sys/riscv/riscv.ld.in
  sys/riscv/signal.c
  sys/riscv/start.S
  sys/riscv/thread.c
Labels: accepted, RISC-V
