Repository cahirwpz/mimiker, pull requests merged in 2022-06, with the labels that each got.

#1243 [pmap] Extract common machdep code to single file
  include/aarch64/pmap.h
  include/mips/pmap.h
  include/mips/tlb.h
  include/riscv/pmap.h
  include/riscv/pte.h
  include/sys/_pmap.h
  include/sys/_tlb.h
  include/sys/fdt.h
  include/sys/pmap.h
  include/sys/vm.h
  sys/aarch64/board.c
  sys/aarch64/boot.c
  sys/aarch64/pmap.c
  sys/aarch64/tlb.c
  sys/gen/Makefile
  sys/gen/pmap.c
  sys/kern/fdt.c
  sys/mips/boot.c
  sys/mips/pmap.c
  sys/mips/tlb.c
  sys/riscv/Makefile
  sys/riscv/board.c
  sys/riscv/boot.c
  sys/riscv/pmap.c
  sys/riscv/tlb.c
Labels: review

#1264 [KASAN] Extract common MD code.
  include/aarch64/kasan.h
  include/aarch64/vm_param.h
  include/mips/kasan.h
  include/mips/vm_param.h
  include/sys/kasan.h
  sys/aarch64/boot.c
  sys/kern/kasan.c
  sys/mips/boot.c
Labels: accepted

#1101 e.MMC controller driver for BCM2835
  include/dev/bcm2835_emmcreg.h
  include/dev/bcm2835_gpio.h
  include/dev/bcm2835_gpioreg.h
  include/dev/emmc.h
  sys/drv/Makefile
  sys/drv/bcm2835_emmc.c
  sys/drv/bcm2835_gpio.c
  sys/drv/bcm2835_rootdev.c
  sys/drv/emmc.c
  sys/drv/sdcard.c
Labels: accepted, AArch64

#1271 [dev] Support for the SOC ranges fdt property
  sys/drv/simplebus.c
Labels: accepted

#1273 [RISCV][dev] Fix LiteX VexRiscv rootdev device node assignemnt
  sys/drv/litex_riscv_rootdev.c
Labels: review, RISC-V

#1261 [drv] Fix simplebus.
  include/sys/fdt.h
  sys/drv/simplebus.c
Labels: accepted

#1197 [toolchain] remove unused Dockerfile from toolchain directory
  toolchain/Dockerfile
Labels: accepted

#1268 [vm] Remove kernel vm_map since all kernel mappings are wired
  include/sys/pmap.h
  include/sys/uio.h
  include/sys/vm_map.h
  sys/aarch64/trap.c
  sys/gen/pmap.c
  sys/kern/main.c
  sys/kern/uio.c
  sys/kern/vm_map.c
  sys/mips/trap.c
  sys/riscv/trap.c
  sys/tests/uiomove.c
  sys/tests/vm_map.c
Labels: accepted

#1265 [RISCV] KASAN implementation.
  build/arch.riscv.mk
  include/riscv/pmap.h
  include/riscv/vm_param.h
  sys/riscv/Makefile
  sys/riscv/boot.c
  sys/riscv/riscv.ld.in
Labels: review, RISC-V

#1267 [trap] Extract common page fault handler
  include/sys/context.h
  include/sys/pmap.h
  sys/aarch64/context.c
  sys/aarch64/trap.c
  sys/gen/pmap.c
  sys/mips/context.c
  sys/mips/trap.c
  sys/riscv/mcontext.c
  sys/riscv/trap.c
Labels: accepted

#1272 [aarch64][dev] Simplebus support
  include/dev/bcm2835reg.h
  sys/aarch64/timer.c
  sys/drv/Makefile
  sys/drv/bcm2835_emmc.c
  sys/drv/bcm2835_pic.c
  sys/drv/bcm2835_rootdev.c
  sys/drv/pl011.c
  sys/dts/rpi3.dts
  sys/kern/bus.c
Labels: accepted, AArch64

#1256 [RISC-V] Physical address map implementation
  include/aarch64/pmap.h
  include/mips/pmap.h
  include/riscv/pmap.h
  include/sys/_pmap.h
  sys/gen/pmap.c
  sys/riscv/pmap.c
  sys/riscv/tlb.c
Labels: accepted, RISC-V

#1275 [kern/malloc]: Remove unused variable.
  sys/kern/malloc.c
Labels: review

#1122 [kevent 3/5] kevent implementation
  include/sys/event.h
  sys/kern/event.c
Labels: accepted

#1250 [RISCV] Integrate RV32 build with GitHub Actions
  .github/workflows/default.yml
  Dockerfile
  Makefile
  build/arch.riscv.mk
  toolchain/gnu/riscv32-mimiker-elf/Makefile
Labels: accepted, RISC-V

#1279 [initrd] Access initrd using dmap
  sys/kern/initrd.c
Labels: accepted

#1281 [RISCV] 64-bit pmap implementation
  include/riscv/pmap.h
  sys/riscv/pmap.c
Labels: accepted, RISC-V

#1282 [RISCV] Sifive Unleashed build target.
  build/arch.riscv.mk
  config.mk
  sys/riscv/riscv.ld.in
Labels: accepted, RISC-V

#1124 [kevent 4/5] Implement select syscall as a wrapper of kevent
  include/sys/fd_set.h
  include/sys/select.h
  lib/libc/sys/select.c
Labels: review

#1285 [RISCV] Remove faulty CSR immediate macros.
  include/riscv/riscvreg.h
Labels: accepted, RISC-V

#1286 [RISCV] Fix virtual memory boot phase entry.
  sys/riscv/boot.c
Labels: accepted, RISC-V

#1289 [RISCV] Enhance the GNU toolchain to include RISC-V 64.
  Dockerfile
  Makefile
  toolchain/gnu/config.mk
  toolchain/gnu/riscv64-mimiker-elf/Makefile
Labels: review, RISC-V

#1287 [RISCV][dev] PLIC support for SiFive Unleashed.
  sys/drv/plic.c
Labels: review, RISC-V

#1255 [lib] Remove strncpy from kernel and use strlcpy instead
  include/sys/libkern.h
  sys/kern/devfs.c
  sys/kern/proc.c
  sys/libkern/stdlib/strtoul.c
  sys/libkern/string/Makefile
Labels: accepted
