Repository cahirwpz/mimiker, pull requests merged in 2022-07, with the labels that each got.

#1292 [dev] Fix return value of simplebus interrupt processing function.
  sys/drv/simplebus.c
Labels: bug, accepted

#1258 [launch] Pass bootargs via dts
  launch
  sys/dts/rpi3.dts
Labels: review

#1280 [physmem] Access vm_page_t structs using dmap.
  include/riscv/vm_param.h
  sys/aarch64/boot.c
  sys/kern/vm_physmem.c
  sys/riscv/boot.c
Labels: review

#1127 Port stdvga to devnode interface
  bin/mandelbrot/mandelbrot.c
  contrib/doom/01-vga-output.patch
  lib/libc/gen/pause.c
  sys/drv/stdvga.c
  sys/kern/vfs_syscalls.c
Labels: accepted

#1148 Pipe non-block tests
  bin/utest/main.c
  bin/utest/pipe.c
  bin/utest/utest.h
  sys/kern/file_syscalls.c
  sys/kern/pipe.c
  sys/kern/syscalls.c
  sys/tests/utest.c
Labels: review

#1295 Sidebar link fix
  wiki/docs/_Sidebar.md
Labels: bug

#1296 [RISCV] Support for kernel tools.
  sys/kern/kgprof.c
  sys/riscv/Makefile
Labels: review, RISC-V

#1168 Make rpi3 as default board.
  config.mk
  launch
  run_tests.py
Labels: accepted, AArch64

#1293 [RISCV] Add SiFive Unleashed to the launch script.
  launch
Labels: accepted, RISC-V

#1301 Enable KASAN on build with Clang
  .github/workflows/default.yml
  build/arch.aarch64.mk
  build/arch.mips.mk
  build/arch.riscv.mk
  build/flags.kern.mk
  build/tools.mk
  include/sys/cdefs.h
  include/sys/mimiker.h
  lib/libc/stdlib/merge.c
  lib/libc/stdlib/qsort.c
  lib/libm/src/s_scalbn.c
  sys/kern/kasan.c
  sys/libkern/stdlib/qsort.c
  sys/riscv/boot.c
  sys/riscv/riscv.ld.in
  sys/riscv/start.S
  sys/riscv/trap.c
Labels: accepted

#1085 [physmem] Describe page size calculation.
  sys/kern/vm_physmem.c
Labels: accepted

#1298 [RISCV][debug] Enable thread backtrace.
  sys/debug/ctx.py
Labels: accepted, RISC-V

#1302 Make boot process on RISC-V and AArch64 similar (pt.1)
  include/sys/cdefs.h
  include/sys/mimiker.h
  sys/aarch64/aarch64.ld
  sys/aarch64/board.c
  sys/aarch64/boot.c
  sys/aarch64/start.S
  sys/riscv/board.c
  sys/riscv/boot.c
  sys/riscv/start.S
Labels: review

#1307 [RISCV] Use sstatus register value from user context in ctx_switch
  sys/riscv/switch.S
Labels: accepted, critical

#1299 [dts] SiFive Unleashed
  launch
  sys/dts/sifive_u.dts
  toolchain/qemu-mimiker/Makefile
  toolchain/qemu-mimiker/patches/cmdline-set-dts-bootargs.patch
  toolchain/qemu-mimiker/patches/series
Labels: review, RISC-V

#1310 Bump up GH Actions to Clang 14
  Dockerfile
  Makefile
  build/arch.riscv.mk
  build/tools.mk
  include/sys/mimiker.h
  sys/aarch64/boot.c
  sys/kern/initrd.c
  sys/kern/proc.c
  verify-format.sh
Labels: critical

#1311 [test] Remove obsolete keyboard test.
  bin/Makefile
  bin/test_kbd/Makefile
  bin/test_kbd/test_kbd.c
Labels: accepted

#1306 Move DTB to kernel bss section on boot
  include/riscv/boot.h
  include/riscv/cpufunc.h
  include/sys/boot.h
  include/sys/fdt.h
  include/sys/mimiker.h
  sys/aarch64/board.c
  sys/aarch64/boot.c
  sys/gen/Makefile
  sys/gen/boot.c
  sys/kern/fdt.c
  sys/mips/board.c
  sys/mips/boot.c
  sys/riscv/board.c
  sys/riscv/boot.c
Labels: accepted

#1314 Switch AArch64 build from gcc to clang
  .github/workflows/default.yml
  config.mk
  lib/libc/gen/aarch64/_setjmp.S
Labels: AArch64

#1315 Bump up QEmu version to 6.2.0
  Makefile
  build/arch.aarch64.mk
  launch
  lib/libc/sys/aarch64/sc_error.S
  sys/aarch64/trap.c
  sys/kern/klog.c
  sys/kern/signal.c
  toolchain/qemu-mimiker/Makefile
  toolchain/qemu-mimiker/debian/changelog
  toolchain/qemu-mimiker/patches/cmdline-set-dts-bootargs.patch
  toolchain/qemu-mimiker/patches/fix-virtual-clock-in-gdb.patch
  toolchain/qemu-mimiker/patches/gdbstub-stop-on-sigxcpu.patch
  toolchain/qemu-mimiker/patches/page-table-walk-for-gdb.patch
Labels: AArch64, critical

#1316 [dev] Implement evdev device grabbing.
  sys/drv/evdev.c
Labels: accepted

#1096 [evdev 3/3] Import evtest program
  contrib/Makefile
  contrib/evtest/.gitignore
  contrib/evtest/01.patch
  contrib/evtest/Makefile
  contrib/evtest/versionsort.c
Labels: accepted

#1128 Port dev cons & null & zero to devnode interface
  sys/drv/dev_cons.c
  sys/kern/dev_null.c
  sys/kern/devfs.c
  sys/tests/vfs.c
Labels: review

#1126 Port evdev to devnode interface
  include/sys/devfs.h
  sys/drv/evdev.c
  sys/kern/devfs.c
Labels: review

#1317 build/tools: call ccache cc instead of ccache ccache cc
  build/tools.mk
Labels: accepted

#1318 build/tools: s/cache/ccache/
  build/tools.mk
Labels: accepted

#1277 Driverize GPIO and set-up pins using FDT
  include/dev/bcm2835_gpio.h
  include/sys/fdt.h
  sys/drv/bcm2835_emmc.c
  sys/drv/bcm2835_gpio.c
  sys/drv/bcm2835_rootdev.c
  sys/drv/pl011.c
  sys/dts/rpi3.dts
  sys/kern/fdt.c
Labels: accepted

#1308 [RISCV] Run tests in CI for SiFive Unleashed
  .github/workflows/default.yml
  run_tests.py
  sys/dts/sifive_u.dts
  sys/kern/fdt.c
  sys/riscv/board.c
Labels: review, RISC-V

#1270 Make README contain more useful information about the project
  README.md
  wiki/docs/Home.md
  wiki/docs/_Sidebar.md
  wiki/docs/building.md
  wiki/docs/malta.md
  wiki/docs/running.md
  wiki/docs/toolchain.md
Labels: accepted
