Repository cahirwpz/mimiker, pull requests merged in 2022-08, with the labels that each got.

#1321 build: flags cleanup
  lib/libc/Makefile
  lib/libterminfo/Makefile
  sys/aarch64/Makefile
  sys/contrib/libfdt/Makefile
  sys/drv/Makefile
  sys/gen/Makefile
  sys/libkern/builtins/Makefile
  sys/libkern/ctype/Makefile
  sys/libkern/stdio/Makefile
  sys/libkern/stdlib/Makefile
  sys/libkern/string/Makefile
  sys/mips/Makefile
  sys/riscv/Makefile
  sys/tests/Makefile
  usr.bin/id/Makefile
  usr.bin/login/Makefile
  usr.bin/su/Makefile
Labels: accepted

#1322 [dev] Resource management simplification.
  include/dev/malta.h
  include/sys/bus.h
  include/sys/device.h
  include/sys/interrupt.h
  include/sys/rman.h
  sys/aarch64/timer.c
  sys/drv/82371AB.c
  sys/drv/atkbdc.c
  sys/drv/bcm2835_emmc.c
  sys/drv/bcm2835_gpio.c
  sys/drv/bcm2835_pic.c
  sys/drv/bcm2835_rootdev.c
  sys/drv/clint.c
  sys/drv/gt64120.c
  sys/drv/liteuart.c
  sys/drv/malta_rootdev.c
  sys/drv/ns16550.c
  sys/drv/pci.c
  sys/drv/pit.c
  sys/drv/pl011.c
  sys/drv/plic.c
  sys/drv/riscv_rootdev.c
  sys/drv/rtc.c
  sys/drv/rtl8139.c
  sys/drv/sifive_uart.c
  sys/drv/simplebus.c
  sys/drv/stdvga.c
  sys/drv/uhci.c
  sys/kern/Makefile
  sys/kern/bus.c
  sys/kern/device.c
  sys/kern/interrupt.c
  sys/kern/rman.c
  sys/mips/timer.c
Labels: accepted

#1325 [mem] Remove the size argument from vmem_free.
  include/sys/kmem.h
  include/sys/vmem.h
  sys/kern/kmem.c
  sys/kern/vmem.c
  sys/tests/pmap.c
  sys/tests/vmem.c
Labels: accepted

#1324 [mem] Add a procedure to obtain the size of a pointed vmem segment.
  include/sys/kmem.h
  include/sys/vmem.h
  sys/kern/kmem.c
  sys/kern/vmem.c
Labels: accepted

#1327 [lockdep] Create a separate lock class for kernel pmap.
  sys/gen/pmap.c
Labels: bug, accepted

#1326 [vmem] Boundary tag allocator.
  include/sys/kmem.h
  include/sys/kmem_flags.h
  include/sys/pmap.h
  include/sys/vm.h
  include/sys/vmem.h
  sys/aarch64/boot.c
  sys/gen/pmap.c
  sys/kern/kasan.c
  sys/kern/kmem.c
  sys/kern/tmpfs.c
  sys/kern/vm_physmem.c
  sys/kern/vmem.c
  sys/mips/boot.c
  sys/riscv/boot.c
  sys/tests/pmap.c
  sys/tests/vmem.c
Labels: review
