Repository cahirwpz/mimiker, pull requests merged in 2022-11, with the labels that each got.

#1349 Fix kernel concurrency sanitizer under Clang
  build/flags.kern.mk
  sys/kern/kcsan.c
Labels: bug

#1348 [RISC-V] Smarter update kernel part of user top PD
  include/aarch64/armreg.h
  include/aarch64/pmap.h
  include/mips/pmap.h
  include/sys/_pmap.h
  sys/gen/pmap.c
  sys/kern/vm_map.c
  sys/riscv/pmap.c
Labels: RISC-V

#1323 [mem] Kmalloc slab allocator.
  include/sys/malloc.h
  include/sys/pool.h
  include/sys/vmem.h
  sys/debug/kdump.py
  sys/debug/memory.py
  sys/drv/pci.c
  sys/drv/riscv_rootdev.c
  sys/kern/kmem.c
  sys/kern/main.c
  sys/kern/malloc.c
  sys/kern/pool.c
  sys/kern/vmem.c
Labels: accepted

#1345 [execve] Set protection bits during ELF load
  bin/utest/Makefile
  bin/utest/main.c
  bin/utest/utest.h
  bin/utest/vm_map_prot.c
  include/mips/m32c0.h
  include/mips/tlb.h
  launch
  sys/aarch64/pmap.c
  sys/debug/cpu.py
  sys/kern/exec_elf.c
  sys/kern/vm_map.c
  sys/mips/boot.c
  sys/mips/cpu.c
  sys/mips/pmap.c
  sys/mips/trap.c
  sys/tests/utest.c
Labels: accepted

#1358 Fix crash during bootstrap when compiled with GCC
  sys/aarch64/boot.c
Labels: AArch64

#1135 Machine-independent SD card driver
  include/dev/sd.h
  sys/drv/sd.c
  sys/dts/rpi3.dts
Labels: review

#1284 emmc: Maintain internal error state and nop when not sane
  include/dev/bcm2835_emmcreg.h
  include/dev/emmc.h
  sys/drv/bcm2835_emmc.c
Labels: accepted

#1360 preempt_enable could switch out with interrupts disabled
  include/sys/sched.h
  sys/kern/interrupt.c
  sys/kern/sched.c
  sys/kern/sleepq.c
Labels: bug
