Repository cahirwpz/mimiker, pull requests merged in 2022-09, with the labels that each got.

#1329 [dev] BAR address should be size-aligned.
  sys/drv/pci.c
Labels: bug, review

#1328 [evdev] Fix evtest build.
  contrib/evtest/Makefile
Labels: bug

#1331 Update uio_offset in devfs read/write operations
  sys/kern/devfs.c
Labels: accepted

#1332 [dev] Basic USB HUB support.
  include/dev/usb.h
  sys/drv/usb.c
Labels: accepted

#1305 [usb] Fix UHCI pool size calculation.
  sys/drv/uhci.c
Labels: bug, review

#1139 [usb] HID mouse driver.
  launch
  sys/drv/Makefile
  sys/drv/hidms.c
Labels: review

#1333 [usb] HID keyboard LED management.
  include/dev/usb.h
  include/dev/usbhid.h
  sys/drv/usb.c
Labels: accepted

#1118 [usb] Mass storage device driver.
  include/dev/scsi.h
  include/dev/umass.h
  launch
  sys/drv/Makefile
  sys/drv/umass.c
Labels: accepted

#1134 [usb] HID keyboard driver.
  launch
  sys/drv/Makefile
  sys/drv/atkbdc.c
  sys/drv/hidkbd.c
Labels: review

#1336 [lockdep][RISCV] Fix pmap lock acquiring order.
  sys/riscv/pmap.c
Labels: bug, accepted, RISC-V
