Repository cahirwpz/mimiker, pull requests merged in 2023-01, with the labels that each got.

#1368 New functions and changes needed for suckless sbase
  include/limits.h
  include/stdio.h
  include/stdlib.h
  include/sys/ioctl.h
  lib/libc/stdio/fmemopen.c
  lib/libc/stdlib/llabs.c
  lib/libc/string/aarch64/bcopy.S
  lib/libc/sys/creat.c
Labels: review

#1369 Tests with signals upgrade
  bin/utest/exceptions.c
  bin/utest/signal.c
  sys/tests/utest.c
Labels: review

#1373 Fix kernel memory allocation on large blocks
  include/sys/syslimits.h
  sys/kern/kmem.c
  sys/kern/malloc.c
Labels: accepted

#1375 Latest changes for sbase
  bin/cat/cat.c
  include/limits.h
  include/stddef.h
  include/sys/common_int_fmtio.h
  include/sys/types.h
  include/sys/unistd.h
  lib/libc/gen/sysconf.c
  sys/drv/pci.c
Labels: accepted

#1377 Employ CHECK_SIG* macros in signal tests. Fix addresses reported by trap handlers.
  bin/utest/exceptions.c
  bin/utest/signal.c
  bin/utest/util.h
  sys/aarch64/trap.c
  sys/mips/trap.c
Labels: accepted

#1374 Userspace test framework overhaul (part 1)
  .gdbinit-test
  .github/workflows/default.yml
  bin/utest/access.c
  bin/utest/cred.c
  bin/utest/exceptions.c
  bin/utest/fd.c
  bin/utest/fork.c
  bin/utest/fpu_ctx.c
  bin/utest/getcwd.c
  bin/utest/lseek.c
  bin/utest/main.c
  bin/utest/misbehave.c
  bin/utest/mmap.c
  bin/utest/pgrp.c
  bin/utest/pipe.c
  bin/utest/procstat.c
  bin/utest/pty.c
  bin/utest/sbrk.c
  bin/utest/setjmp.c
  bin/utest/sigaction.c
  bin/utest/signal.c
  bin/utest/stat.c
  bin/utest/time.c
  bin/utest/tty.c
  bin/utest/utest.c
  bin/utest/utest.h
  bin/utest/util.c
  bin/utest/util.h
  bin/utest/vfs.c
  bin/utest/vm_map.c
  bin/utest/vm_map_prot.c
  bin/utest/wait.c
  config.mk
  launch
  lib/libc/gen/ualarm.c
  sys/debug/README.md
  sys/debug/klog.py
  sys/tests/utest.c
Labels: critical

#1378 [sleepq] Add a mutex to the sleepq wait interface.
  include/sys/sleepq.h
  sys/drv/rtc.c
  sys/kern/callout.c
  sys/kern/condvar.c
  sys/kern/interrupt.c
  sys/kern/signal.c
  sys/kern/sleepq.c
  sys/kern/time.c
  sys/tests/sleepq.c
  sys/tests/sleepq_abort.c
  sys/tests/sleepq_timed.c
  sys/tests/thread_stats.c
  sys/tests/turnstile_adjust.c
Labels: accepted

#1376 Fix error returned from getresuid and getresgid
  bin/utest/cred.c
  sys/kern/syscalls.c
Labels: bug, accepted
