Repository cahirwpz/mimiker, pull requests merged in 2023-05, with the labels that each got.

#1383 vm: Fix prot check in vm_page_fault
  sys/kern/vm_map.c
Labels: bug, review

#1370 Implement mprotect syscall
  bin/utest/Makefile
  bin/utest/mmap.c
  bin/utest/mprotect.c
  bin/utest/util.c
  bin/utest/util.h
  include/mips/tlb.h
  include/sys/vm.h
  include/sys/vm_map.h
  sys/aarch64/pmap.c
  sys/kern/exec_elf.c
  sys/kern/mmap.c
  sys/kern/syscalls.c
  sys/kern/vm_map.c
  sys/tests/utest.c
Labels: review

#1384 Add clangd files to `.gitignore`
  .gitignore
Labels: proposal

#1380 libc changes for suckless sbase
  include/sys/stat.h
  include/sys/syscall.h
  include/sys/syscallargs.h
  include/sys/time.h
  include/time.h
  lib/libc/gen/readdir.c
  lib/libc/sys/syscalls.S
  lib/libc/time/localtime.c
  lib/libc/time/private.h
  lib/libc/time/strptime.c
  sys/kern/syscalls.c
  sys/kern/syscalls.master
  sys/kern/sysent.h
Labels: accepted

#1385 proc: Free `p_args` from proper kmalloc pool
  sys/kern/proc.c
Labels: bug, accepted

#1084 Kgprof profclock
  include/sys/kgprof.h
  include/sys/time.h
  sys/drv/pit.c
  sys/kern/clock.c
  sys/kern/kgprof.c
Labels: review, orphaned
