Repository cahirwpz/mimiker, pull requests merged in 2023-07, with the labels that each got.

#1398 pathconf syscall
  include/sys/syscall.h
  include/sys/syscallargs.h
  include/sys/vfs.h
  include/sys/vnode.h
  lib/libc/sys/syscalls.S
  sys/kern/initrd.c
  sys/kern/syscalls.c
  sys/kern/syscalls.master
  sys/kern/sysent.h
  sys/kern/tmpfs.c
  sys/kern/vfs_syscalls.c
  sys/kern/vfs_vnode.c
Labels: accepted

#1400 sbase: add getconf and hostname
  contrib/sbase/Makefile
  include/sys/syslimits.h
  include/unistd.h
  lib/libc/gen/gethostname.c
  lib/libc/gen/sethostname.c
Labels: review

#1399 tty: add TIOCNOTTY ioctl
  contrib/sinit/patches/series
  contrib/sinit/patches/sinit.patch
  include/sys/ttycom.h
  sys/kern/tty.c
Labels: review

#1392 vm: Copy on write
  include/sys/vm_amap.h
  include/sys/vm_map.h
  sys/gen/pmap.c
  sys/kern/vm_amap.c
  sys/kern/vm_map.c
Labels: accepted

#1409 Parallel test runner for userspace tests
  bin/utest/main.c
  bin/utest/utest.c
  bin/utest/utest.h
Labels: WiP
